"""Переименовано поле

Revision ID: 272b71514f2a
Revises: f155fe274ece
Create Date: 2025-12-13 17:58:50.342525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272b71514f2a'
down_revision: Union[str, Sequence[str], None] = 'f155fe274ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('famous_persons', sa.Column('russian_text', sa.Text(), nullable=True))
    op.drop_column('famous_persons', 'russain_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('famous_persons', sa.Column('russain_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('famous_persons', 'russian_text')
    # ### end Alembic commands ###
