"""initial migration

Revision ID: eda5bc7db7ea
Revises: 
Create Date: 2025-12-13 15:21:48.445368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda5bc7db7ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('famous_persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('english_url', sa.String(length=512), nullable=False),
    sa.Column('english_name', sa.String(length=256), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('russian_url', sa.String(length=512), nullable=True),
    sa.Column('russian_name', sa.String(length=256), nullable=True),
    sa.Column('russain_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('english_url')
    )
    op.create_index(op.f('ix_famous_persons_english_name'), 'famous_persons', ['english_name'], unique=False)
    op.create_index(op.f('ix_famous_persons_russian_name'), 'famous_persons', ['russian_name'], unique=False)
    op.create_index(op.f('ix_famous_persons_russian_url'), 'famous_persons', ['russian_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_famous_persons_russian_url'), table_name='famous_persons')
    op.drop_index(op.f('ix_famous_persons_russian_name'), table_name='famous_persons')
    op.drop_index(op.f('ix_famous_persons_english_name'), table_name='famous_persons')
    op.drop_table('famous_persons')
    # ### end Alembic commands ###
