"""Добавили флаг-индикатор отправки

Revision ID: f155fe274ece
Revises: eda5bc7db7ea
Create Date: 2025-12-13 15:43:10.573833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f155fe274ece'
down_revision: Union[str, Sequence[str], None] = 'eda5bc7db7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('famous_persons', sa.Column('sent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_famous_persons_sent'), 'famous_persons', ['sent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_famous_persons_sent'), table_name='famous_persons')
    op.drop_column('famous_persons', 'sent')
    # ### end Alembic commands ###
